# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_tenants_to_users'),
        ('ipam', '0018_remove_service_uniqueness_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregate',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aggregates', to='tenancy.Tenant'),
        ),
        migrations.AddField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='tenancy.Tenant'),
        ),
    ]
