# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-18 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0019_add_tenant_to_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlangroup',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vlan_groups', to='dcim.Site'),
        ),
    ]
