# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_add_tenancy_view_permissions'),
        ('ipam', '0020_remove_vlan_group_null_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='vrf',
            name='rd',
            field=models.CharField(max_length=21, verbose_name='Route distinguisher'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set([('tenant', 'slug'), ('tenant', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='vrf',
            unique_together=set([('rd', 'tenant')]),
        ),
    ]
