# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_tenants_to_users'),
        ('circuits', '0009_unicode_literals'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='providers', to='tenancy.Tenant'),
        ),
    ]
