# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_add_tenancy_view_permissions'),
        ('circuits', '0010_add_tenant_to_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='provider',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='provider',
            unique_together=set([('tenant', 'slug'), ('tenant', 'name')]),
        ),
    ]
