# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import utilities.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_add_tenancy_view_permissions'),
        ('dcim', '0044_add_tenant_to_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='asset_tag',
            field=utilities.fields.NullableCharField(blank=True, help_text='A unique tag used to identify this device', max_length=50, null=True, verbose_name='Asset tag'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=utilities.fields.NullableCharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='devicerole',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='devicerole',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='asset_tag',
            field=utilities.fields.NullableCharField(blank=True, help_text='A unique tag used to identify this item', max_length=50, null=True, verbose_name='Asset tag'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='platform',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='rackrole',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rackrole',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='site',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterUniqueTogether(
            name='device',
            unique_together=set([('rack', 'position', 'face'), ('tenant', 'name'), ('tenant', 'asset_tag')]),
        ),
        migrations.AlterUniqueTogether(
            name='devicerole',
            unique_together=set([('tenant', 'name'), ('tenant', 'slug')]),
        ),
        migrations.AlterUniqueTogether(
            name='devicetype',
            unique_together=set([('manufacturer', 'model', 'tenant'), ('manufacturer', 'slug', 'tenant')]),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together=set([('device', 'asset_tag'), ('device', 'parent', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='platform',
            unique_together=set([('tenant', 'name'), ('tenant', 'slug')]),
        ),
        migrations.AlterUniqueTogether(
            name='rackrole',
            unique_together=set([('tenant', 'name'), ('tenant', 'slug')]),
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together=set([('tenant', 'name'), ('tenant', 'slug')]),
        ),
    ]
