# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-10 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0005_add_tenancy_view_permissions'),
        ('extras', '0007_unicode_literals'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageattachment',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='tenancy.Tenant'),
        ),
    ]
