# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 18:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenancy', '0003_unicode_literals'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='tenants', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
