# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 08:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('tenancy', '0003_unicode_literals'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantgroup',
            name='access_group',
            field=models.ManyToManyField(blank=True, related_name='tenant_group', to='auth.Group', verbose_name='Access Group'),
        ),
        migrations.AddField(
            model_name='tenantgroup',
            name='access_users',
            field=models.ManyToManyField(blank=True, related_name='tenant_group', to=settings.AUTH_USER_MODEL, verbose_name='Access Users'),
        ),
    ]
