# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_tenants_to_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['group', 'name'], 'permissions': (('view', 'Can see tenant options'),)},
        ),
    ]
