# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0003_unicode_literals'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secret',
            options={'ordering': ['device', 'role', 'name'], 'permissions': (('view', 'Can see Secret options'),)},
        ),
    ]
